[build]
command = "pnpm install --frozen-lockfile && pnpm build"
publish = ".next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "18"

[[plugins]]
package = "@netlify/plugin-nextjs"
