name: Portfolio Sync & Deploy (Netlify)

on:
  # 1) run when you push changes to the portfolio repo (main branch)
  push:
    branches: [ main ]
    # only run when site-relevant files change (edit as you like)
    paths:
      - "app/**"
      - "components/**"
      - "data/**"
      - "public/**"
      - "scripts/**"
      - "styles/**"
      - "next.config.*"
      - "package.json"
      - "pnpm-lock.yaml"
      - "netlify.toml"
      - ".github/workflows/portfolio-sync.yml"
  # 2) manual button in Actions tab
  workflow_dispatch:
  # 3) daily
  schedule:
    - cron: "0 6 * * *"
  # 4) when project repos ping via repository_dispatch
  repository_dispatch:
    types: [project_updated]

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run sync (generate new project files only)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PORTFOLIO_GH_USER: ${{ vars.PORTFOLIO_GH_USER }}
          INCLUDE_TOPICS: "true"
          MAX_REPOS: "100"
        run: node scripts/sync.mjs

      - name: Commit new project entries (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/projects/*.json || true
          git diff --cached --quiet || git commit -m "chore(data): add new project entries"
          git push

      # Build & deploy using netlify.toml's resolved publish dir (.next for your static build)
      - name: Build & Deploy to Netlify
        run: npx netlify deploy --build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
